services:
  docker:
    image: docker:26.1.1-dind
    privileged: true

steps:
  run-compose:
    image: docker:26.1.1
    when:
      event:
        - push
        - manual
    environment:
      DOCKER_HOST: tcp://docker:2376
    commands:
      - apk add --no-cache docker-compose
      - docker-compose up -d
      - curl http://localhost:8181/message/get